apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB1_PORT: 'MzMwNg=='
  DB1_URL: 'YXotYS5oeXVuZGIuOWJkNjk1OWU1YWQ0NGVhYTkxNWI3N2M0YWMxNmE1ZGIubXlzcWwubWFuYWdlZC1zZXJ2aWNlLmtyLWNlbnRyYWwtMi5rYWthb2Nsb3VkLmNvbQ=='
  DB1_ID: 'YWRtaW4='
  DB1_PW: 'YWRtaW4xMjM0'
  DB2_PORT: 'MzMwNw=='
  DB2_URL: 'YXotYi5oeXVuZGIuOWJkNjk1OWU1YWQ0NGVhYTkxNWI3N2M0YWMxNmE1ZGIubXlzcWwubWFuYWdlZC1zZXJ2aWNlLmtyLWNlbnRyYWwtMi5rYWthb2Nsb3VkLmNvbQ=='
  DB2_ID: 'YWRtaW4='
  DB2_PW: 'YWRtaW4xMjM0'